# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Setup ssh authorization
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$PUBLIC_KEY" | tr -d '\r' > ~/.ssh/id_rsa.pub
          chmod 644 ~/.ssh/id_rsa.pub
          echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          echo SSH agent started
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
          ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts

      - name: Update
        run: ssh ${{secrets.USERNAME}}@${{secrets.HOST}} "cd lab-tw-2b4 && git pull"
      - name: Cleanup
        run: rm -rf ~/.ssh
